apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://github.com/Vivien87/aks-app-deploy.git"
    targetRevision: HEAD
    path: k8s-manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
