apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets-provider
  namespace: default
spec:
  provider: azure
  parameters:
    
    keyvaultName: "Volodymyr"  
    objects: |
      array:
        - |
          objectName: "newSecret"  
          objectType: "secret"  # (secret, key, certificate)
    usePodIdentity: "false" 
    tenantId: "8d1157bb-1f96-415f-824b-ab0a29485d7d" 